### ISSUE TITLE
Lien mort show_this_exercise

### ISSUE THREAD

**Issue by chayr** [philippedemaria/sacado#3]
dans la liste :
https://sacado.xyz/qcm/exercises

lien mort si je clique sur ce lien d'excercice : 
https://sacado.xyz/qcm/show_this_exercise/1016/

il y a l'erreur suivante dans le log :

`Internal Server Error: /qcm/show_this_exercise/1016/
Traceback (most recent call last):
  File "/home/c1398844c/virtualenv/sacado/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/c1398844c/virtualenv/sacado/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/c1398844c/virtualenv/sacado/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/c1398844c/sacado/qcm/views.py", line 1676, in show_this_exercise
    exercise = Exercise.objects.get(id=id)
  File "/home/c1398844c/virtualenv/sacado/3.7/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/c1398844c/virtualenv/sacado/3.7/lib/python3.7/site-packages/django/db/models/query.py", line 417, in get
    self.model._meta.object_name
qcm.models.Exercise.DoesNotExist: Exercise matching query does not exist.`

pas d'exercice avec un id 1016 dans la base : 
![image](https://user-images.githubusercontent.com/3321967/84605827-fdba5b00-ae65-11ea-986c-1b01525e4337.png)

**Comment by chayr** [comment]
réglé, pb dans le template qcm/list_exercice.html
