### ISSUE TITLE
500 ajax populate dans la sélection des exercices lors de la 2ème requete consecutive **line 240, in ajax_populate    e.students.add(student)**

### ISSUE THREAD

**Issue by chayr** [philippedemaria/sacado#5]
url :
https://sacado.xyz/qcm/parcours_peuplate/461/#

erreur 500 lors du 2 ème clic sur le checkbox
![image](https://user-images.githubusercontent.com/3321967/84606198-5e976280-ae69-11ea-9a8d-76a2caab1ebc.png)

log : **line 240, in ajax_populate    e.students.add(student)**

Traceback (most recent call last):
  File "/home/c1398844c/virtualenv/sacado/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/c1398844c/virtualenv/sacado/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/c1398844c/virtualenv/sacado/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/c1398844c/virtualenv/sacado/3.7/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/c1398844c/sacado/qcm/views.py", line 240, in ajax_populate
    e.students.add(student)
AttributeError: 'Exercise' object has no attribute 'students'

**Comment by chayr** [comment]
problème avec ajax_level_exercise aussi
![image](https://user-images.githubusercontent.com/3321967/84832168-646c7f80-aff2-11ea-9d2f-0ffa65a00a5d.png)

**Comment by philippedemaria** [comment]
for student in students :
                r.students.remove(student)
